app.clientId=b5584636-dc7a-4ac3-a6cc-b87a5a4ed345
app.tenantId=f48f3d07-3f20-4bb7-9a75-1af76fd0983a
app.clientSecret=5ZI8Q~JH~9evxsSH0ht_Jf5nnbV8EYnySGbBIbuL
app.graphUserScopes=Calendars.Read,openid,profile,offline_access,User.Read